spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: category-service
              uri: lb://CATEGORY-SERVICE
              predicates:
                - Path=/category-service/v3/api-docs/**, /api/v1/categories/**
              filters:
                - RewritePath=/category-service/(?<remaining>.*), /${remaining}

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product-service/v3/api-docs/**, /api/v1/products/**
              filters:
                - RewritePath=/product-service/(?<remaining>.*), /${remaining}

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth-service/v3/api-docs/**, /api/v1/auths/**, /api/v1/users/**
              filters:
                - RewritePath=/auth-service/(?<remaining>.*), /${remaining}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://35.209.164.72:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: "${spring.application.name}:${server.port}"

server:
  port: 8088

springdoc:
  swagger-ui:
    urls:
      - name: category-service
        url: /category-service/v3/api-docs

      - name: product-service
        url: /product-service/v3/api-docs

      - name: auth-service
        url: /auth-service/v3/api-docs

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      enabled: true
  zipkin:
    tracing:
      enabled: true
      endpoint: http://35.209.164.72:9411/api/v2/spans
      connect-timeout: 5s
      read-timeout: 10s
      flush-interval: 1000
      batch-size: 10
      compression:
        enabled: true